### ISSUE TITLE
Remove references to particular servers from README

### ISSUE THREAD

**Issue by paramat** [KaiGerdMueller/minetest-bot-collection#1]
Please remove any references to particular servers from the README, as currently you are providing cheating code and encouraging it's use on a particular server.

**Comment by KaiGerdMueller** [comment]
Why? Is there any law/rule that forces me to do that? This project's main use is to be used on this server... also, i don't link to my github account on minetest forums (i only link to my loth project wich was removed from the forums because of to your nice licensing paragraph!). therefore, It's absolutely ok to mention it's only purpose. also, first I did'nt want to go that far... (packaging the cheating tool took much time). I just made a little guideline about how to get around csm mod security (wich can't be disabled, sadly :( ). of course you can use it to build a cheat... but you can also use it for many other purposes (for example, to enable writing files) . nice sfan5 gave me a warning! and therefore i packaged it. It's a huge revenge.

**Comment by paramat** [comment]
Why? Decency and consideration.

MT forum moderators may decide you are a malicious member of the community, which you seem to be (for example see your reply above), and ban you.
Also this forum rule:

"Hacking/Cheating: It is not permissible to promote, link, or otherwise direct Forum users to any kind of "hacking" or "cheating" tools, regardless of their claimed purpose."

You may not currently promoting cheats on the forum, but have done intensively recently and many will be curious and will have found your Github account, as i did, and you continue to promote those cheats here, but even worse, specify the server to use them on. The server is that of a co-owner of the MT GitHub organisation and a forum moderator too.
The forum rules do not state you have to be promoting cheats on the forum, you could be promoting them elsewhere.

So you're in a risky situation. I'm not even asking you to delete the cheats, just remove references to a specific server, i'm being quite lenient.

@rubenwardy

**Comment by KaiGerdMueller** [comment]
- ' "hacking" or "cheating" tools ' - TOOLS! °~°

on forums i just published a guideline that can be (mis)used that way! no TOOL! °~°
(aldough it was partly designed for misuse) >: )

- "The server is that of a co-owner of the MT GitHub organisation and a forum moderator too." -_-

If there was true justice the offended persons identity should make no difference. O.O
+
I knew all the time. - _ -
+
I don't care, too. - _ -


- "The forum rules do not state you have to be promoting cheats on the forum, you could be promoting them elsewhere." -_-

The forum rules don't define a punishment either >: )
+
It is obvious (aldough not stated) that this rule is only about actions on the forums. °0°


- Also, if you want me to change anything: °_°

You can't force me to do anything. -_-
+
You have to convince me that what I do is wrong. O.O


- Also, concerning "@rubenwardy": -_-

I think he already knows. ^_^


- this is no exploit!


- Take home message : °_°

Don't try to put pressure on me, it does not work! -_-
+
Trying to suppress others is no good character trade. ^ _ ^


- +TODAY MY BOT COLLECTION HAS UNIQUE VISITOR COUNT RECORD! THAT MUST BE CELEBRATED! ^ _ ^ :{ ) :{ ) :{ )

**Comment by KaiGerdMueller** [comment]
since there are no new arguments I close the issue.
